name: Deploy production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to production (live)
    runs-on: ubuntu-latest
    if: github.repository == 'hedgerow-dev/web'
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to production
        run: firebase deploy --only hosting --project hedgerow-908c7 --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
